go:
  version: 1.15.6
repository:
  path: github.com/swoga/alertmanager-filter
build:
  binaries:
    - name: alertmanager-filter
      path: ./cmd/alertmanager-filter
  flags: -tags netgo -trimpath
  ldflags: |
    -w -s
    -X github.com/swoga/alertmanager-filter/version.Version={{.Version}}
    -X github.com/swoga/alertmanager-filter/version.Revision={{.Revision}}
tarball:
  files:
    - LICENSE
    - NOTICE
    - example.yml
crossbuild:
  platforms:
    - linux/amd64